name: Backend Wake Up

on:
  schedule:
    - cron: "*/14 * * * *"
  workflow_dispatch:

jobs:
  poke_server:
    runs-on: ubuntu-latest
    steps:
      - name: Poke Backend Server
        run: curl -sf https://slang-dictionary-p04y.onrender.com/api/models || curl -sf https://slang-dictionary-p04y.onrender.com/
